### ISSUE TITLE
Hard-coded path to JSON in wheel.js

### ISSUE THREAD

**Issue by jamestelfer** [dastergon/wheel-of-misfortune#13]
See [wheel.js:16](https://github.com/dastergon/wheel-of-misfortune/blob/ecf347dfec36fb7c2f475b27405ddca26d1d90b4/static/wheel.js#L16). In my clone, I changed it to `./incidents/general_incidents.json` and it then referenced the local file correctly.

I'm not 100% sure that's the right fix however.

**Comment by dastergon** [comment]
Good catch! I fixed it in my latest commit, thank you very much 👍
